### PR TITLE
Only Old Norse texts

### PR DESCRIPTION
**Pull request by clemsciences**
I removed English texts from this repository. Only Old Norse texts should be kept. Or maybe they should be  clearly seperated from Old Norse texts. Anyway, we expect here Old Nose texts and English texts can bring mistakes if we do any global analysis on Old Norse texts.

### CODE REVIEW

**Comment by clemsciences** [comment]
Hey @kylepjohnson, 
May Germanic team members have write access on Germanic copora repositories ?

**Comment by kylepjohnson** [comment]
Hi Clément, I though you had write access already :)

I have given you write access to both our ON repos in the Germanic Team: https://github.com/orgs/cltk/teams/germanic/repositories

Please let me know if you need admin for the Germanic group and I'll give it to you.

Please try to merge this PR yourself, to test if the permissions are good. Thank you!

**Comment by clemsciences** [comment]
Done! I got write access for this repository, thanks! As I'm the only one to be active in the Germanic group and that I have time to manage any requests in this group, I'd like to be admin of the Germanic group.

**Comment by kylepjohnson** [comment]
I looked and it seems there is no admin level for Teams (e.g., Germanic), however I've made you admin of both https://github.com/cltk/old_norse_text_perseus/ and https://github.com/cltk/old_norse_models_cltk/ . You can add new repos under Germanic too, and to those you'll have full read/write access.

Thanks and let me know if something doesn't look right!

**Comment by clemsciences** [comment]
Perfect

**Pull request merged**
